######################## default configuration ####################
baseURL = "/"
languageCode = "en-us"
title = "lornamariak"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"

  
############################## navigation ###############################
[menu]
  
  # main menu
  [[menu.main]]
  name = "About"
  URL = "about/about"
  weight = 3
  
  [[menu.main]]
  name = "Posts"
  URL = "blog"
  weight = 2

  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about/about"
  weight = 3
  
  [[menu.footer]]
  name = "Posts"
  URL = "blog"
  weight = 2
  
  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 4


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"

# Meta data
description = "This is meta description"
author = "Lorna Maria"
# Google Analitycs
googleAnalitycsID = "UA-154356124-1"

# Contact Information
mobile = 2345786554
email = "lornamariak@gmail.com"
location = "Around the Globe"
# copyright
copyright = "Lorna Maria | [Themefisher](https://themefisher.com) All Rights Reserved"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = false

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join Our Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"

############################# social site ########################

[[params.social]]
title = "Twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/lornamariak"


[[params.social]]
title = "Github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/lornamariak"

[[params.social]]
title = "Linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/lornamaria/"
